### ISSUE TITLE
Authorization header not in request

### ISSUE THREAD

**Issue by vischlatter** [jackfranklin/fetch-factory#22]
If you add headers to your request, e. g. Authorization, the headers are not in the generated request.

**Comment by jackfranklin** [comment]
Can you show me your code / link me to some code that I can recreate?

**Comment by kapa1017** [comment]
I think u should use the pickBy() method instead of pick():

 removeNullFetchOptions(options) {
    return pick(options, (v, k) => v != null && !isEmpty(v));
              ^^^
  }

this is maybe because of your lodash dependency! You should update your package.json and use pickBy() instead of pick().

**Comment by vischlatter** [comment]
Thank you for the quick reply.

Sorry for the missing context. I wanted to send you a pull request instantly. But then I found out, that it is a dependency problem on our side as stated by kapa1017.

We have lodash 4.16.4 as a dependency. Within this version they splitted the pick method you are using. If you want to pass a filter method you have to use the newly introduced pickBy method.

So, I think you can close the issue as the problem is on our side. You might want to consider updating your dependencies.

BTW, nice lib, helped us a lot. :thumbsup:

**Comment by vischlatter** [comment]
One last thing. babel-tape-runner has been updated to 1.3.1. With this version, you can't start the tests. Version 1.3.0 is still working, with one failing test. :wink:

```
/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/project/node_modules/babel-tape-runner/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by jackfranklin** [comment]
If anyone would like to PR  a Lodash update that would be really cool.

I think I should move the tests over to Jest; I much prefer it these days.

**Comment by vischlatter** [comment]
Ok, I will see if I can get it done tommorow. I will file another issue for this and send you a PR.
